### PR TITLE
Feature/redesign about view

### LINKED ISSUE #4328: Redesign System/About View
It's ugly and the inner container scrolls, when exceeding viewport. So we should come up with a visual redesign.

Screen Shot 2021-03-01 at 15 23 49

### PR DESCRIPTION
**Pull request by flourish86**
Resolves #4328

### CODE REVIEW

**Comment by nilmerg** [comment]
Please reference the issue with `resolves`

**Comment by flourish86** [comment]
Resolves #4496

**Review by nilmerg — APPROVED** [review]

**Comment by flourish86** [comment]
Thanks for taking over.

It's good how the width grows, with more content in the cells.

Can we make the "configure" buttons in `@icinga-blue`? See #4683

I also noticed another thing: If there's really long cell content the content width exceeds the viewport's width. Maybe this is not a problem in most cases, but it could be glitchy on narrower screen sizes.

Screen Shot 2022-02-28 at 09 32 15

**Comment by nilmerg** [comment]
> I also noticed another thing

The commit id is of fixed length, that won't happen.

**Comment by flourish86** [comment]
> > I also noticed another thing
> 
> The commit id is of fixed length, that won't happen.

Ok, seems to work in all screen widths, then.

**Pull request merged**
