### PR TITLE
Enable PHP CodeSniffer in travis testing

### PR DESCRIPTION
**Pull request by lazyfrosch**
* [x] Enable phpcs test on every build
* [x] Update phpcs, except for PHP 5.3
* [x] Speed up travis builds by only requiring sudo on precise
* [x] Code cleanup and rule update
* [x] Update icingacli test commands

### CODE REVIEW

**Comment by lazyfrosch** [comment]
Hm the rule ref didn't work correctly...

**Comment by lazyfrosch** [comment]
It's green<sup>TM</sup>

@lippserd please review, and merge?

**Comment by lippserd** [comment]
Could you do me a big favour and move the top-level xml files to the test directory? I just don't see why they should pollute the root directory. Is phpcs happy if we add `/** @noinspection PhpMissingBreakStatementInspection */` above the offending case statements instead of adding a comment inside the cases?

**Comment by lazyfrosch** [comment]
Updated the comments.

Seems like phpcs doesn't like the config the be in another location, it's always using relative paths to the dirname of the config...

**Comment by lippserd** [comment]
Hi Markus,

Our icingacli test commands should consider those phpcs config files too. Could you also take care of that please?

Cheers,
Eric

**Comment by lazyfrosch** [comment]
@lippserd updated the commits accordingly

We should fix https://github.com/Icinga/icinga-packaging/issues/50 for the 2.5.0 package release.

**Pull request merged**
