### PR TITLE
Don't call session_start() after ini_set()

### LINKED ISSUE #3185: PHP 7.2 Support?
After updating PHP to version 7.2.0 icingaweb2 does not work anymore

```
Fatal error: Uncaught ErrorException: session_name(): Cannot change session name when session is active in .../icingaweb2/library/Icinga/Web/Session/PhpSession.php:97 Stack trace:
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'session_name():...', '/usr/share/weba...', 97, Array)
#1 .../icingaweb2/library/Icinga/Web/Session/PhpSession.php(97): session_name('Icingaweb2')
#2 .../icingaweb2/library/Icinga/Web/Session/PhpSession.php(152): Icinga\Web\Session\PhpSession->open()
#3 .../icingaweb2/library/Icinga/Web/Controller/ActionController.php(544): Icinga\Web\Session\PhpSession->write()
#4 .../icingaweb2/library/Icinga/Web/Controller/ActionController.php(489): Icinga\Web\Controller\ActionController->shutdownSession()
#5 .../icingaweb2/library/vendor/Zend/Controller/Action.php(512): Icinga\Web\Controller\ActionController->postDispatch()
#6 .../icingaweb2/library/Icinga/Web in .../icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 332
```

## Your Environment
```
:~ > icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.3-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Arch Linux ARM
  Platform version: Unknown
  Kernel: Linux
  Kernel version: 4.14.3-1-ARCH
  Architecture: armv7l
```

Icingaweb2 version is 2.4.1 on archlinux.

Will there be a php 7.2 support soon?

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #3185

### CODE REVIEW

**Comment by reubenfarrelly** [comment]
Confirming - this patch completely fixes the php-7.2 issue for me - I've been running with this patch for some weeks now against -master, with no other problems.  Hopefully this patch can be merged soon.

**Comment by pillbug22** [comment]
We recently updated to Ubuntu 18.04, and are experiencing the same issue as this bug report was for. 

- After the upgrade, /etc/apt/sources.list.d/icinga.list was updated from icinga-xenial to icinga-bionic
- apt update shows everythig up to date
- the output of running Icinga2 at CLI shows version r2.8.4-1

Are there additional steps we need to take to implement this fix?

**Comment by dnsmichi** [comment]
Wait until 2.6 is officially released, or use the patchset as a workaround meanwhile.

**Comment by pillbug22** [comment]
Thanks - is it still ETA end of this month for 2.6? Just trying to decide if we can limp along until 2.6, or we need to roll back to PHP 7.1?

**Comment by lippserd** [comment]
@pillbug22 Yes I think we can manage that 😄

**Pull request merged**
