### PR TITLE
Interpret performance data threshold ranges

### LINKED ISSUE #2587: [dev.icinga.com #12885] Performance Data omits Warn/Crit values
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12885

**Created by rajo01 on 2016-10-10 17:58:55 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-10 17:58:55 +00:00 (in Redmine)_

---

I'm using the check\_pcmeasure2.pl script to measure some temperature values. On the command line, they display as expected:

        /usr/lib/nagios/plugins/check_pcmeasure2.pl -H 192.168.xx.xx -S com1.1 -w 16:24 -c 10:30
        PCMEASURE WARNING - value = 15.4 | value=15.4;16:24;10:30

Also, when looking into the icinga\_servicestatus table, the complete data is logged there, e.g.:

        PCMEASURE OK - Temperatur = 22.7  |             | temperatur=22.7;15.1:32.1;15:32    

But for whatever reason, icingaweb2 displays just 0 ... Any ideas?

For the record, I'm using Icinga2 2.5.4-1 and icingaweb2 2.3.4 of packages.icinga.org

**Attachments**

* [broken_perfdata.png](https://dev.icinga.com/attachments/download/3679/broken_perfdata.png) rajo01 - _2016-10-10 17:57:35 +00:00_

---

**Relations**:

* blocks [#12885](https://dev.icinga.com/issues/12885)

### PR DESCRIPTION
**Pull request by nilmerg**
proper-threshold-interpretation

fixes #2587

### CODE REVIEW

**Comment by nilmerg** [comment]
Rebased the old branch with the current master. Looks good so far.

As @Al2Klimov mentioned in the old issue #1298 only tests are missing. Since we've decided to only show the raw threshold values ( @lippserd ) we don't need any pretty printing.

The advantage of these changes is that we're able to visualize the state on pie-charts correctly. Without these any pie-chart would be green even if the state is warning/critical.

**Comment by lippserd** [comment]
Could you add a test case for invalid ranges as well please? Everything else looks good.

**Comment by nilmerg** [comment]
Wasn't sure how we're supposed to handle invalid ranges as they're part of a plugin's perfdata and as such already evaluated. However, there's a test now which checks if invalid notations are at least rendered as-is. Evaluation is not tested as I really don't want to define what's wrong or right in such cases.

```
s\Icinga\Module\Monitoring\Plugin\ThresholdRange
 [x] From string properly parses double exclusive ranges
 [x] Contains correctly evaluates double exclusive ranges
 [x] From string properly parses single exclusive ranges
 [x] Contains correctly evaluates single exclusive ranges
 [x] From string properly parses inclusive ranges
 [x] Contains correctly evaluates inclusive ranges
 [x] From string properly parses empty thresholds
 [x] Contains evaluates everything to true for empty thresholds
 [x] Invalid threshold notations are rendered as is
```

**Comment by lippserd** [comment]
Thanks for the extensive tests. I'll merge the PR now.

**Pull request merged**
