### PR TITLE
added feature required expire time

### PR DESCRIPTION
**Pull request by GrexAut**
added config parameter "acknowledge_expire_required" for setting "Use expire Time", so clients have to set an expire time at acknowleding the problem

### CODE REVIEW

**Comment by GrexAut** [comment]
signed

**Comment by bobapple** [comment]
@cla-bot check

**Review by nilmerg — CHANGES_REQUESTED** [review]
Please add documentation.

**Comment by nilmerg** [comment]
If you plan to continue here, please re-open.

**Pull request closed without merging**
