### PR TITLE
Correct documentation about icingacli

### PR DESCRIPTION
**Pull request by rgevaert**
icingacli is its own package on Debian and Ubuntu too.

### CODE REVIEW

**Comment by dnsmichi** [comment]
@lazyfrosch did we split them up lately?

**Comment by lazyfrosch** [comment]
@dnsmichi We did way back: https://anonscm.debian.org/cgit/pkg-nagios/pkg-icingaweb2.git/commit/?id=672fcae6a067078e31e521bc61d1e3a1bf4591ac

**Comment by lazyfrosch** [comment]
But since 2.5.0 `icingacli` is also a dependency of `icingaweb2` on RPM...

**Comment by dnsmichi** [comment]
Ah ok, thanks for the clarification.

**Pull request merged**
