### PR TITLE
GHA: handle changed interface of Icinga/docker-icingaweb2

### PR DESCRIPTION
**Pull request by Al2Klimov**
## TODO

* Icinga/docker-icingaweb2#109

### CODE REVIEW

**Comment by nilmerg** [comment]
> which one does not simply re-tag

I was not talking about re-tagging.

Look here:

* https://github.com/Icinga/icingaweb2/actions/runs/4016267509
* https://github.com/Icinga/icingaweb2/actions/runs/4016266725

Both ran at the same time. Why is there a technical limitation so that they can't run in parallel anymore?

> the GHA is going to create short version tags by itself

Ah, so https://github.com/Icinga/icingaweb2/blob/master/RELEASE.md#docker is obsolete?

**Comment by Al2Klimov** [comment]
> Why is there a technical limitation so that they can't run in parallel anymore?

The upcoming auto re-tagging.

> Ah, so https://github.com/Icinga/icingaweb2/blob/master/RELEASE.md#docker is obsolete?

Not yet.

**Comment by nilmerg** [comment]
Okay, fine. Don't explain it. I don't merge it.

**Comment by Al2Klimov** [comment]
See discussion here: https://github.com/Icinga/icinga2/pull/9625#issuecomment-1384252188

**Comment by lippserd** [comment]
> See discussion here: [Icinga/icinga2#9625 (comment)](https://github.com/Icinga/icinga2/pull/9625#issuecomment-1384252188)

No, you provide the answer to his question here.

**Comment by lippserd** [comment]
Justification and explanation for this PR is missing.

**Comment by Al2Klimov** [comment]
> And what purpose has the concurrency group then?

To be honest: the auto re-tagging hasn’t been even committed yet for IW2.

Fixed the PR.

**Review by nilmerg — APPROVED** [review]

**Pull request merged**
