### PR TITLE
Add links in hosts and services lists to show all listed objects

### LINKED ISSUE #2344: [dev.icinga.com #11309] Allow to bulk execute monitoring actions based on the current filter without need to list or select objects
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11309

**Created by koudis on 2016-03-04 14:43:16 +00:00**

Assignee: _elippmann_
Status: _Feedback_ 
Target Version: _Backlog_
Last Update: _2016-12-15 17:17:08 +00:00 (in Redmine)_

---

Hi,
I would like to be able to to set schedule downtime or acknowledge based on filter without need to list or select objects.

Scenario:
In Service Problems I will add some filter setting and create specific filter with 5k+ services in it. I want to do action on all of them without the need to view and select all services.

**Changesets**

_2016-12-15 17:14:01 +00:00_ by _(unknown)_ a88822cb1479606174e65c108e576c3d67198410

    Add links in hosts and services lists to show all listed objects
    
    This allows executing bulk actions without having selected all of them manually.
    
    refs #11309

---

**Relations**:

* duplicates [#11309](https://dev.icinga.com/issues/11309)
* blocks [#8584](https://dev.icinga.com/issues/8584)

### PR DESCRIPTION
**Pull request by Al2Klimov**
This allows executing bulk actions without having selected all of them manually.

fixes #2344

### CODE REVIEW

**Comment by lippserd** [comment]
We should not waste space for this link. At the moment the link is displayed beneath the filter editor. In my opinion we have two options. We may either add this link to the dropdown menu or add it as button right next to the open filter editor icon. @Thomas-Gelf and @flourish86 What's your opinion on this one?

**Comment by Al2Klimov** [comment]
As discussed w/ @lippserd (offline):

Unfortunately the show actions' downtime counters' filtering capabilities aren't as powerful as the lists' ones. (See e.g. http://localhost:8080/icingaweb2/monitoring/hosts/show?host_problem=1)

**Comment by helmo** [comment]
+1 for showing the new link next to the open filter editor icon.
An icon might be nice though.

A gimp impression of what it would look like:
selection_058

**Comment by ekeih** [comment]
In the current version of Icingaweb2 it is not possible to do this with several hundred services at the same time because the URL gets to long. I guess the same applies for this new (and very helpful) feature. So maybe it would be a good idea to execute this as a POST request.

**Pull request closed without merging**
