### PR TITLE
IcingaException::getConfidentialTraceAsString(): don't fail on internal functions

### LINKED ISSUE #3318: Confidential StackTrace breaks on some errors
For example a simple PHP error like: `preg_replace_callback(): Unknown modifier 'g'` will break the behavior:

bildschirmfoto von 2018-01-25 13-57-28

```
( ! ) Fatal error: Uncaught exception 'ErrorException' with message 'Undefined index: file' in /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 332
--



1 | 0.3261 | 264736 | {main}( ) | .../index.php:0
2 | 0.3340 | 295560 | require_once( '/usr/share/icingaweb2/library/Icinga/Application/webrouter.php' ) | .../index.php:4
3 | 0.3821 | 4639424 | Icinga\Application\Web->dispatch( ) | .../webrouter.php:104
4 | 0.3821 | 4640808 | Zend_Controller_Front->dispatch( ???, ??? ) | .../Web.php:407
5 | 0.5369 | 15405728 | Zend_Controller_Plugin_Broker->postDispatch( ??? ) | .../Front.php:948
6 | 0.5369 | 15405728 | Zend_Controller_Plugin_ErrorHandler->postDispatch( ??? ) | .../Broker.php:329
7 | 0.5369 | 15405728 | Zend_Controller_Plugin_ErrorHandler->_handleError( ??? ) | .../ErrorHandler.php:222



1 | 0.3261 | 264736 | {main}( ) | .../index.php:0
2 | 0.3340 | 295560 | require_once( '/usr/share/icingaweb2/library/Icinga/Application/webrouter.php' ) | .../index.php:4
3 | 0.3821 | 4639424 | Icinga\Application\Web->dispatch( ) | .../webrouter.php:104
4 | 0.3821 | 4640808 | Zend_Controller_Front->dispatch( ???, ??? ) | .../Web.php:407
```

Reverting the confidential stacktrace lines in ErrorController prints the normal stacktrace :wink: 

@Al2Klimov can you have a look?

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.5.1 / master

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #3318

### CODE REVIEW

**Comment by lazyfrosch** [comment]
Found another error, not sure what caused it:

```
ErrorException: Undefined variable: messages in /usr/share/icingaweb2/application/views/scripts/error/error.phtml on line 15
```

**Comment by lazyfrosch** [comment]
Note: The error was generated due to a missing IndexController, but this does not explain why not handled :)

**Comment by lazyfrosch** [comment]
Also: `http://localhost:8080/icingaweb2/blalba`

**Comment by Al2Klimov** [comment]
@lazyfrosch #3321

**Pull request merged**
