### PR TITLE
RecursiveNavigationRenderer#__toString(): show whole stacktrace on error

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
https://github.com/Icinga/icingaweb2/issues/4211#issuecomment-669816909

**Comment by Al2Klimov** [comment]
Commit based on v2.8.0 for eventual backporting via merge.

**Comment by nilmerg** [comment]
Please use master as base. I also don't think showing the stacktrace is necessary so please only log the exception as error.

**Comment by Al2Klimov** [comment]
We're already showing just the exception. Why do you think this isn't neccessary?

**Comment by nilmerg** [comment]
Because it clutters the view. The single line `describe` produces suffices to show the user something is wrong. The stacktrace doesn't provide any more advantage. If necessary one can then take a look in the log and the full stacktrace is available.

**Comment by nilmerg** [comment]
Oh, and please stop the assignee ping pong. Mentioning me is enough if I'm not participating already.

**Comment by Al2Klimov** [comment]
> The stacktrace doesn't provide any more advantage.

Fine...

**Pull request closed without merging**
