### PR TITLE
Make comments and downtimes instance aware

### LINKED ISSUE #3076: Comment deletion to wrong instance
I still have a multi instance setup here.

When try to deleting a comment, the command is sent to the wrong instance (the first only)

Also it seems `DEL_HOST_COMMENT` is the wrong command here :wink: 

```
[1510215688] EXTERNAL COMMAND: DEL_HOST_COMMENT;401584
```

### PR DESCRIPTION
**Pull request by lazyfrosch**
This is mostly a compatibility patch for multi-instance setups of the IDO.

There Icinga Web couldn't always decide which instance to send the command to.

Please review @lippserd 

fixes #3076

### CODE REVIEW

**Comment by lazyfrosch** [comment]
@lippserd please review and merge

**Comment by lazyfrosch** [comment]
Seems like there is still a problem deleting multiple downtimes at once.

**Comment by lazyfrosch** [comment]
Fixed the named problem with 62bff08

**Comment by lazyfrosch** [comment]
poke @lippserd please merge

**Comment by nilmerg** [comment]
As mentioned in #3076, closed.

**Pull request closed without merging**
