### PR TITLE
Docs: Add global URL parameters to advanced topics

### LINKED ISSUE #2190: [dev.icinga.com #10810] Document how to hide menu and header
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10810

**Created by Anonymous on 2015-12-09 19:12:07 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-02-17 17:39:44 +00:00 (in Redmine)_

---

It would be great if it was possible to hide Menu and Header from the view when you use Icingaweb2 to show the status in Operations Centre environments or on monitors generally as "read only".

---

**Parent Task:** [#7153](https://dev.icinga.com/issues/7153)

### PR DESCRIPTION
**Pull request by dnsmichi**
fixes #2190

### CODE REVIEW

**Comment by dnsmichi** [comment]
@lippserd please let me know if there are more global URL parameters. It is hard to track down with reverse engineering. Also if `_disableLayout` should be added to the docs or not.

**Comment by nbuchwitz** [comment]
I would add ```format=sql```, which I find quite helpfull when narrowing down database specific errors (like postgresql specific ```group by``` errors).

**Comment by dnsmichi** [comment]
Thanks, added the format=sql entry.

**Comment by lippserd** [comment]
Hi Michi,

Thanks for the docs so far. We should not add `_disableLayout` to the list. It is a pure framework related parameter.

Cheers,
Eric

**Comment by dnsmichi** [comment]
Thanks @lippserd thought so, this comes from the ZendFramework. Removed it.

URL parameters for specific controllers/views need to be added separately I think.

**Comment by Thomas-Gelf** [comment]
@dnsmichi: it's not from Zend, it's ours :p It's a parameter used solely for internal purposes. There are others, related to rendering instructions or feature detection. I think the ones you have chose for the documentation are exactly the ones we need there, thank you!

**Comment by dnsmichi** [comment]
Thanks, that'll be one of the documentation updates coming in for 2.5 :)

**Pull request merged**
