### PR TITLE
Fix issue #4789. Sort roles in by name

### PR DESCRIPTION
**Pull request by w1ll-i-code**
Add a column 'name' with the name of the role to the role array so that it is possible to sort the roles by name.

### CODE REVIEW

**Comment by w1ll-i-code** [comment]
Hi, is there something missing for this PR? please let me know so I can fix it in case.

**Comment by nilmerg** [comment]
For a start, a signed CLA ;)

**Comment by nilmerg** [comment]
Any update?

**Comment by lippserd** [comment]
@cla-bot check

**Comment by lippserd** [comment]
CLA was signed just recently for an Icinga 2 PR.

**Comment by nilmerg** [comment]
Your proposed changes are not quite correct. But they pointed me in the correct direction to actually understand the underlying problem. So I took the chance to fix this on my own, as I broke it as well originally. :blush: (#5285)

**Pull request closed without merging**
