### PR TITLE
Custom variable rendering hooks

### LINKED ISSUE #3479: Display the Director Caption of a Custom Variable
## Expected Behavior

Display the "Caption" of a custom variable in IcingaWeb2.

## Current Behavior

We define our "Data Fields" with the Icinga Director and want to display the "Caption" in IcingaWeb2
datafield

IcingaWeb2 currently display the "Field Name" of custom variable.
customvariable

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.5.3
* Version used (`icinga2 --version`):  r2.8.4-1

### PR DESCRIPTION
**Pull request by nilmerg**
resolves #3479

### CODE REVIEW

**Comment by fl0wx** [comment]
@nilmerg is it possible that this PR can solve this issue too? https://github.com/Mikesch-mp/icingaweb2-module-grafana/issues/281 (if implemented correctly in grafana module?).

**Comment by nilmerg** [comment]
@fl0wx No, this is only about what is shown in the monitoring module. The end result of either implementation has no effect on who implements it. (i.e. the grafana module)

**Comment by fl0wx** [comment]
@nilmerg ok thanks. Any suggestions who else could help with my issue? There is unfortunately no activity on the issue and im out of ideas.

**Comment by nilmerg** [comment]
https://community.icinga.com might be a good start ;)

**Comment by fl0wx** [comment]
@nilmerg thanks and i already did that: https://community.icinga.com/t/grafana-module-issue-maintaining-of-grafana-module/9138 Hopefully someone will react. Is there anything i can do if no one will react there too? Sorry for spamming this PR.

**Pull request merged**
