### PR TITLE
Allow disabling MySQL server certificate validation by setting ssl_do_not_verify_server_cert

### PR DESCRIPTION
**Pull request by marianrh**
…

### CODE REVIEW

**Comment by lippserd** [comment]
Hi,

Thanks for your PR. The proposed changes look good to me. Unfortunately the constant `MYSQL_ATTR_SSL_VERIFY_SERVER_CERT` seems to be unavailable in PHP 5.6 which is our minimum supported version. Could you please add a `defined('\PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT')` to all places where you access the constant and the corresponding resource config? Do you know when this constant was introduced? We should mention this in the docs too.

Cheers,
Eric

**Comment by marianrh** [comment]
@lippserd Hi Eric, thanks for looking at the PR! I now implemented the `defined('\PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT')` checks as you suggested. Unfortunately I couldn't find any proper documentation for the constant. I added a remark to `04-Resources.md` that it's only available on PHP versions greater than 5.6.

**Comment by marianrh** [comment]
@lippserd Hi Eric, can I do anything else to get this merged? Thanks!

**Comment by lippserd** [comment]
Hi,

We'll merge this PR after the 2.6.2 release. Thanks again for your contribution.

Best,
Eric

**Pull request merged**
