### PR TITLE
add canceled downtimes to the history, if they were started

### PR DESCRIPTION
**Pull request by Robnarok**
fixes https://github.com/Icinga/icingaweb2/issues/5176

### CODE REVIEW

**Comment by Robnarok** [comment]
i have signed the CLA

**Comment by bobapple** [comment]
@cla-bot check

**Comment by nilmerg** [comment]
@gianlucapiccolo @mcodato This is the exact opposite of https://github.com/Icinga/icingaweb2/commit/db9888b1f1380355c68d759b59844e17b0241043. Please have a look here and add your thoughts.

**Comment by Robnarok** [comment]
i took another look at the implementation, and if i understand it correctly, the current behavior is:

```
if a downtime has started and is not cancelled it is displayed
if a downtime has started and is cancelled it is NOT displayed
if a downtime has NOT started and is cancelled it is NOT displayed
if a downtime has NOT started and is NOT cancelled it is NOT displayed
```
removing the AND part like i did in the current PR, it would lead to

```
if a downtime has started and is NOT cancelled it is displayed
if a downtime has started and is cancelled it is displayed
if a downtime has NOT started and is cancelled it is NOT displayed
if a downtime has NOT started and is NOT cancelled it is NOT displayed
```
or a third solution could be if we would replace the AND with an OR (`was_started=1 OR was_cancelled=0`) we would get something like
```
if a downtime has started and is NOT cancelled it is displayed
if a downtime has started and is cancelled it is displayed
if a downtime has NOT started and is cancelled it is NOT displayed
if a downtime has NOT started and is NOT cancelled it is displayed
```

**Comment by mcodato** [comment]
Hi @Robnarok, I see your point, the change we made was for another very annoying bug, let me do some internal tests and talk about it with my colleagues and I will let you know as soon as possible, thank you

**Comment by mcodato** [comment]
@Robnarok Thank you for your patience, the tests showed that your PR is fine for us, as it keeps the `was_started = 1`  :)

**Comment by nilmerg** [comment]
@Robnarok Please rebase with main, this *should* fix the actions

**Comment by Robnarok** [comment]
@mcodato  Thank you for testing :) 

@nilmerg i did the rebase and the actions passed :partying_face:

**Review by nilmerg — APPROVED** [review]

**Pull request merged**
