### PR TITLE
navigation/dashboard.phtml: Use ipl-web's Icon for fa- icons

### LINKED ISSUE #5277: Support fontawesome icons for navigation dashboards not only for Icinga DB Web
## Is your feature request related to a problem? Please describe.
Navigation dashboards (Click on a menu item with sub-entries) support fontawesome icons, but only if the url starts with `icingadb/`.

## Describe the solution you'd like
Any other item, irrespective of its URL, should be able to reference fontawesome icons.

### PR DESCRIPTION
**Pull request by nilmerg**
resolves #5277

### CODE REVIEW

**Comment by nilmerg** [comment]
requires https://github.com/Icinga/ipl-web/pull/232

**Comment by moreamazingnick** [comment]
since the branch is called fa-icons for everyone...
does this fit into that?
#5205

**Comment by nilmerg** [comment]
In theory, for menu items, yes. Patching `url.php` makes not much sense to me, it's legacy code and links with fontawesome icons are constructed differently nowadays.

**Review by raviks789 — APPROVED** [review]

**Comment by nilmerg** [comment]
@moreamazingnick Now it does fit.
@raviks789 I've added the map as discussed recently.

**Review by raviks789 — APPROVED** [review]

**Pull request merged**
