### PR TITLE
Locale files in spanish for icingaweb

### PR DESCRIPTION
**Pull request by Juanito87**
I'm not a translator, but users at my office requested if spanish localization was posible, so i give it a go, I hope it's usefull.

### CODE REVIEW

**Comment by nilmerg** [comment]
Useful? That's a most welcome addition! Thank you :+1: 

Only thing I'm missing at the moment are the compiled *.mo files. Please commit them as well.

**Comment by nilmerg** [comment]
Oh, and you might want to update your master and update your po files. I'm sure there changed a lot in terms of localization in the recent 13 months :wink:

**Comment by nilmerg** [comment]
Hi, are you still working on this? Just tried this out myself and noticed there are still missing translations. (Probably due to the update of your master)

Version 2.8 (stable) is not yet released, so you still have the chance to get everything into the upcoming release!

Though, I also noticed you've placed the module translations in the wrong place. A module has its own `application/locale/ll_CC/LC_MESSAGES` folder. The monitoring and setup module translations should be placed there.
If you need help with how you should update and test your translations, I'll happily assist. Just tell me where you need help. Maybe also read our [documentation](https://github.com/Icinga/icingaweb2/blob/master/modules/translation/doc/03-Translation.md#translation-for-translators-) (if you haven't already) which covers the basics.

**Comment by Juanito87** [comment]
Sorry I've been quite busy, and had been imposible to take a look at this. When will the release of 2.8 will be?
I'll try to get the translations sort out, and in the proper routes. 
Sorry for this mess, I'm still learning version control and how to contribute to a project.

**Comment by nilmerg** [comment]
There's no exact date for the 2.8 stable yet, but rest assured it probably won't happen until the mid or end of May.

**Comment by nilmerg** [comment]
Hi Juan,

we are currently in the process to move our translation files from separate repositories into a single repository. That's https://github.com/Icinga/L10n.
I'd like you to create a new PR over there instead of here. Though, things are slightly different in the new location so your current progress can't be transferred 1:1.

I'd like to aid you with that by preparing you a file that contains all of your current progress based on the new repository.
Though, in order to do that we should ensure that I really got your current progress as you should continue your work with this file.

So if you still have not committed all your changes, please do that soon and push them into this PR.
In any case please leave me a comment so that I can start preparing the move for you. Thanks!

Best,
Johannes

**Comment by Juanito87** [comment]
You have my current progress. It would be great if you could create the new
file for me. Once I finish that one, I'll create a PR in the new repo.

Regards.
Juan Cruz.

**Comment by nilmerg** [comment]
The file<sup>(1)</sup> is attached. Just extract it in the new repository's location `src/es_AR/LC_MESSAGES/icinga.po`.
Then continue as usual. Though, please make sure to use a proper editor because the file `setup.po` in this PR had a few syntax errors. (They're corrected in the new file)

How the contribution process works in described [here](https://github.com/Icinga/L10n/blob/master/CONTRIBUTING.md).

Oh, and be aware that there are now nearly 4k messages in this combined catalog. Your current progress is around 45% which, honestly, is already a lot. :+1: Don't mind creating the new PR below 100% completion. :wink: 

Thank you!

¹ [icinga.po.zip](https://github.com/Icinga/icingaweb2/files/4558928/icinga.po.zip)

**Comment by nilmerg** [comment]
Hey Juan,

you seem to not have continued here. We'd like to include your work in the upcoming releases, albeit being incomplete. Can I make the transfer to Icinga/L10n for you? Is there any chance you'll continue with the translation?

Best,
Johannes

**Comment by Juanito87** [comment]
I'm sorry, it has been hard to keep up with this. You can make the transfer
to L10n.
With a little luck next month is more decompressed and I can try to get
back to it.

Regards.
Juan Cruz.

**Comment by nilmerg** [comment]
Done: https://github.com/Icinga/L10n/pull/43

**Pull request closed without merging**
