### PR TITLE
group_by support for custom variables (postgres)

### PR DESCRIPTION
**Pull request by nbuchwitz**
Added group_by support for querying customvariablestatus table for hosts
and services in postgresql environments. The bug prevents users to filter the host map by hostgroups or other.

Happy to discuss changes adressing a more generic solution :smiley: 

fixing #1873

### CODE REVIEW

**Comment by nbuchwitz** [comment]
Any chance to review this PR? Due to a requirement in a customer project, it would be nice to have a fix in 2.5.0

**Comment by lippserd** [comment]
Yes sir we'll have a look at this one asap.

**Comment by lippserd** [comment]
@nbuchwitz Would you please share some URLs which are affected by this PR?

**Comment by lippserd** [comment]
@nbuchwitz Sorry but I have to close your PR in favor of this one #3092. Thanks for your efforts though. I would have liked to see you as the author of the fix since you came up with the initial fix but had to change the code so that it does not look like yours anymore.

**Comment by nbuchwitz** [comment]
@lippserd No problem, just happy to have working group by support - no matter who has made the fix

**Comment by lippserd** [comment]
@nbuchwitz Any chance that you test my PR? 😄

**Comment by nbuchwitz** [comment]
@lippserd I'll test today, but first I have to finish some integrations for a customer.

**Comment by nbuchwitz** [comment]
@lippserd I tested the PR against and everything looks good to me. With this PR (and the upcoming 2.5 release)  i could push the filter by hostgroup feature into the map module master. Thanks! :+1:

**Pull request closed without merging**
