### PR TITLE
Detect binary prefix and use for perf data display

### PR DESCRIPTION
**Pull request by theFeu**
refs #3690

### CODE REVIEW

**Comment by nilmerg** [comment]
What's been the rationale for this? Most checks I know of return SI units. Are there any returning IEC ones? If not, does a fix to correct the transformation suffice?

**Comment by lippserd** [comment]
Stalled until Icinga 2 supports writing UOMs with the IEC prefix.

**Comment by nilmerg** [comment]
That's https://github.com/Icinga/icinga2/issues/7225, for reference.

**Comment by nilmerg** [comment]
@lippserd Just noticed.. does it make sense finishing this for the monitoring module? Yes, Icinga DB still depends on monitoring and also utilizes this class but at the time Icinga 2.13 is a thing aren't we also ready/finished having this natively in Icinga DB?

**Comment by lippserd** [comment]
> @lippserd Just noticed.. does it make sense finishing this for the monitoring module? Yes, Icinga DB still depends on monitoring and also utilizes this class but at the time Icinga 2.13 is a thing aren't we also ready/finished having this natively in Icinga DB?

We don't have this automatically in Icinga DB. The performance data is stored unparsed still.
We should implement this together with icinga/icinga2#7225. It is ok though to have this in Icinga DB Web only.

**Comment by nilmerg** [comment]
Then this gets closed.

**Comment by lippserd** [comment]
> Then this gets closed.

Do we have a new issue for Icinga DB Web?

**Pull request closed without merging**
