### PR TITLE
Feature: Enhanced Dashboards

### PR DESCRIPTION
**Pull request by yhabteab**

### CODE REVIEW

**Comment by Yonas-net** [comment]
This PR is depending on the following Branches.

**ipl-web**: ``form-utilities``
**ipl-html**: ``form-enhancements``

and the current version of ``icingadb-web`` master, also ``icingadb`` must be enabled.

**Comment by nilmerg** [comment]
The branches `form-utilities` and `form-enhancements` are now merged into their respective master.

Icinga DB Web is required due to [the `@iplWebAssets` LESS variable](https://github.com/Icinga/icingadb-web/blob/master/public/css/common.less#L3-L5). Since we depend upon ipl the first time in Icinga Web 2 now, we should move this variable definition here.

**Comment by Yonas-net** [comment]
This is only a small part of what is planned for the future, but the current status is as follows. In order to test this PR you have to also check out [this branch](https://github.com/Icinga/ipl-web/pull/13) in **ipl-web**, create a new DB for it and a new IW2  backend. And as long as the old ``DashboardController`` is not dropped, you need to rename the new ``DashboardsController`` to DashboardController. :(

- [ ] From now on you can not create panes or dashlets without a home
- [ ] System panes and dashlets are loaded under `/iw2/dashboard` and `/iw2/dashboard/home`
- [ ] All created homes are listed as list items in the navigation menu of the dashboard
- [ ] System dashlets are stored in the DB only when they are edited by the user
- [ ] Creating a new pane and dashlet in default home
- [ ] Creating a new dashlet in system panes
- [ ] System panes and dashlets can be disabled but not deleted, unless the user have edited them before, in which case
      all changes to them are rolled back
- [ ] Default Home can't be removed by the user
- [ ] It is prohibited to move system panes and dashlets to any other home
- [ ] Creating, editing and removing a new dashboard home, pane, and dashlet
- [ ] User created homes, panes, dashlets can be removed, edited and moved freely.

**Dashboard settings**:
- [ ] All panes, dashlets are listed as before, except that now additionally the home name is listed as well
- [ ] When system panes and dashlets are disabled, a ban icon is displayed next to them.

**Comment by yhabteab** [comment]
Superseded by https://github.com/Icinga/icingaweb2/pull/4702

**Pull request closed without merging**
