### PR TITLE
WIP: Implement transiflex

### PR DESCRIPTION
**Pull request by lazyfrosch**
I wanted to tryout Transifex for translations for Icinga Web and created an account:

https://www.transifex.com/icinga/icingaweb2

If anyone wants to help, join Transifex above and ping me for questions.

Actions:
- [x] Include and handle POT files
- [x] Upload current state to transifex
- [ ] Use relative paths for files (no `/usr/share/...`)
- [ ] Update local documentation

Handling in the future:
* No more manual fiddling with po files
* Update POT files when code changes (can be automated)
* Work on the webserver
* Pull PO files before and releases and compile them

Opinions?

### CODE REVIEW

**Comment by nilmerg** [comment]
Had this much traction in the past months? Doesn't seem so to me, but I don't have an account.

**If** we're integrating this, we should consider guarding all translation calls against malicious strings (as I've already seen and used too many non-escaped `$this->translate()` calls) And having our internationalization this open makes this even more likely to be a serious problem.

**Comment by lazyfrosch** [comment]
It was an experiment, but makes absolutely sense for use to have better translations...

There should be a way to check for escaped strings.

**Comment by nilmerg** [comment]
Of course it makes sense, I'm with you here. But if it's not used I don't see any advantage having it. Our previous translation maintainers did not have much interest here on Github. Adding another platform just to see the same result doesn't make any sense to me, unfortunately. So if there really was *no activity at all* in the past months on transiflex I'd see this experiment as failed.

**Comment by lazyfrosch** [comment]
It is a way better UI than any local software and will allow non-technical people to help us translating.

We told nobody we even use Transifex, so why should anyone? It see it merely as a benefit that translations doesn't need to be done by developers.

**Comment by nilmerg** [comment]
> We told nobody we even use Transifex, so why should anyone?

Then we should do so?

To be clear: I like the idea to have more recent/complete translations. Though what I don't like is the idea of a platform that is either inactive or requires a full time job to maintain. (And that's what it looks like now, previously I had the impression this is some kind of crowdsource platorm)

**Comment by lazyfrosch** [comment]
This is up for adoption when someone wants to implement it

**Comment by nilmerg** [comment]
Transifex is unfortunately not an option for us (anymore). Regarding their terms of use we're not open-source enough to make use of the free plan.

The automation however is still on track, though now in a separate project: https://github.com/Icinga/L10n

**Pull request closed without merging**
