### PR TITLE
Translation updates de_DE

### LINKED ISSUE #3067: de_DE Translation of timestamps
I noticed an incorrect translation in the "time ago" / "at" logic.

image image

Seen on b7639651e80e85b81d9fb92c1db77e90c3754d2d

We should fix this for 2.5 - will have a look and submit PR

### PR DESCRIPTION
**Pull request by lazyfrosch**
fixes #3067

### CODE REVIEW

**Comment by lazyfrosch** [comment]
Current German translations for DateFormatter:

```
+----------+------------+------------+
| TIME AGO |     C      |   DE_DE    |
+----------+------------+------------+
| 15 sec   | 0m 15s ago | vor 0m 15s |
| 62 sec   | 1m 2s ago  | vor 1m 2s  |
| 10 min   | 10m 0s ago | vor 10m 0s |
| 1h       | at 12:52   | um 12:52   |
| 3h       | at 10:52   | um 10:52   |
| 25h      | 1d 1h ago  | vor 1d 1h  |
| 31d      | on Oct 9   | um Oct 9   |
+----------+------------+------------+

+------------+-------------+------------+
| TIME SINCE |      C      |   DE_DE    |
+------------+-------------+------------+
| 15 sec     | for 0m 15s  | für 0m 15s |
| 62 sec     | for 1m 2s   | für 1m 2s |
| 10 min     | for 10m 0s  | für 10m 0s |
| 1h         | since 12:52 | seit 12:52 |
| 3h         | since 10:52 | seit 10:52 |
| 25h        | for 1d 1h   | für 1d 1h |
| 31d        | since Oct 9 | seit Oct 9 |
+------------+-------------+------------+

+------------+-----------+-----------+
| TIME UNTIL |     C     |   DE_DE   |
+------------+-----------+-----------+
| 15 sec     | in 0m 15s | in 0m 15s |
| 62 sec     | in 1m 2s  | in 1m 2s  |
| 10 min     | in 10m 0s | in 10m 0s |
| 1h         | at 14:52  | um 14:52  |
| 3h         | at 16:52  | um 16:52  |
| 25h        | in 1d 1h  | in 1d 1h  |
| 31d        | on Dec 10 | am Dec 10 |
+------------+-----------+-----------+
```

**Comment by lazyfrosch** [comment]
@lippserd please have a look

**Comment by Storagegirl** [comment]
+----------+------------+------------+
| TIME AGO |     C      |   DE_DE    |
+----------+------------+------------+
| 15 sec   | 0m 15s ago | vor 0m 15s |
| 62 sec   | 1m 2s ago  | vor 1m 2s  |
| 10 min   | 10m 0s ago | vor 10m 0s |
| 1h       | at 15:25   | um 15:25   |
| 3h       | at 13:25   | um 13:25   |
| 25h      | 1d 1h ago  | vor 1d 1h  |
| 31d      | on Oct 9   | am Oct 9   |
+----------+------------+------------+

+------------+-------------+------------+
| TIME SINCE |      C      |   DE_DE    |
+------------+-------------+------------+
| 15 sec     | for 0m 15s  | seit 0m 15s |
| 62 sec     | for 1m 2s   | seit 1m 2s |
| 10 min     | for 10m 0s  | seit 10m 0s |
| 1h         | since 15:25 | seit 15:25 |
| 3h         | since 13:25 | seit 13:25 |
| 25h        | for 1d 1h   | seit 1d 1h |
| 31d        | since Oct 9 | seit Oct 9 |
+------------+-------------+------------+

+------------+-----------+-----------+
| TIME UNTIL |     C     |   DE_DE   |
+------------+-----------+-----------+
| 15 sec     | in 0m 15s | in 0m 15s |
| 62 sec     | in 1m 2s  | in 1m 2s  |
| 10 min     | in 10m 0s | in 10m 0s |
| 1h         | at 17:25  | um 17:25  |
| 3h         | at 19:25  | um 19:25  |
| 25h        | in 1d 1h  | in 1d 1h  |
| 31d        | on Dec 10 | am Dec 10 |
+------------+-----------+-----------+

**Comment by lazyfrosch** [comment]
Cleaned up the commits.

Current timestamps:

```
+----------+------------+------------+
| TIME AGO |     C      |   DE_DE    |
+----------+------------+------------+
| 15 sec   | 0m 15s ago | vor 0m 15s |
| 62 sec   | 1m 2s ago  | vor 1m 2s  |
| 10 min   | 10m 0s ago | vor 10m 0s |
| 1h       | at 13:30   | um 13:30   |
| 3h       | at 11:30   | um 11:30   |
| 25h      | 1d 1h ago  | vor 1d 1h  |
| 31d      | on Oct 13  | am Oct 13  |
+----------+------------+------------+

+------------+--------------+-------------+
| TIME SINCE |      C       |    DE_DE    |
+------------+--------------+-------------+
| 15 sec     | for 0m 15s   | seit 0m 15s |
| 62 sec     | for 1m 2s    | seit 1m 2s  |
| 10 min     | for 10m 0s   | seit 10m 0s |
| 1h         | since 13:30  | seit 13:30  |
| 3h         | since 11:30  | seit 11:30  |
| 25h        | for 1d 1h    | seit 1d 1h  |
| 31d        | since Oct 13 | seit Oct 13 |
+------------+--------------+-------------+

+------------+-----------+-----------+
| TIME UNTIL |     C     |   DE_DE   |
+------------+-----------+-----------+
| 15 sec     | in 0m 15s | in 0m 15s |
| 62 sec     | in 1m 2s  | in 1m 2s  |
| 10 min     | in 10m 0s | in 10m 0s |
| 1h         | at 15:30  | um 15:30  |
| 3h         | at 17:30  | um 17:30  |
| 25h        | in 1d 1h  | in 1d 1h  |
| 31d        | on Dec 14 | am Dec 14 |
+------------+-----------+-----------+
```

**Pull request merged**
