### PR TITLE
add MariaDB to requirements

### PR DESCRIPTION
**Pull request by robertsilen**
add MariaDB to requirements, as discussed in https://github.com/Icinga/icingaweb2/issues/5237

### CODE REVIEW

**Comment by bobapple** [comment]
@cla-bot check

**Comment by nilmerg** [comment]
Thank you :D Though, I'm not sure why you picked such an old state. Please adjust this based on `main`.

**Comment by robertsilen** [comment]
The [2.8 installation doc](https://icinga.com/docs/icinga-web/2.8/doc/02-Installation/) implicitly mentions MariaDB in the requirements, so I was trying to add MariaDB there, but looks like this is going into main now. 

For main's [current installation doc](https://icinga.com/docs/icinga-web/latest/doc/02-Installation/) I suggest this PR: https://github.com/Icinga/icingaweb2/pull/5247

Sorry, not sure how to replace these. This one can be closed if you are not accepting it into 2.8?

**Comment by nilmerg** [comment]
2.8 is not supported anymore and as such, changes won't be released nor be included in our official documentation.

**Pull request closed without merging**
