### PR TITLE
Disable dark theme

### PR DESCRIPTION
**Pull request by nilmerg**

### CODE REVIEW

**Comment by sukhwinder33445** [comment]
I checked out to the branch disable-dark-theme. The tabs are not readable because of the white background and the white font colour. This appears when you tab over the tabs.

Screenshot 2021-07-01 at 10 30 20

**Comment by sukhwinder33445** [comment]
Menu items are difficult to read when hovering the mouse over them. (Theme Icinga)

Screenshot 2021-07-05 at 09 31 22

**Comment by nilmerg** [comment]
That's been fixed. Please pull.

**Comment by sukhwinder33445** [comment]
Oh yes, sorry, that was browser chache.

**Pull request merged**
