### PR TITLE
Solarized dark theme

### PR DESCRIPTION
**Pull request by deric**
A dark theme based on [Solarized](http://ethanschoonover.com/solarized). HEX codes for colors are very similar [this guide](http://simianuprising.com/wp-content/uploads/2012/08/solarized-reference-horizontal.png). 

I've copied and modified `high-contrast.less` theme, some of the code might be still simplified.

### CODE REVIEW

**Comment by lazyfrosch** [comment]
I really like the theme, though some colors should be updated still.

Unfortunately some add-ons like Icinga Director have weird colors in the theme. But not your problem as of now.

Do you want to tune more stuff, or should I review and maybe add some minor changes?

**Comment by deric** [comment]
@lazyfrosch Thanks, yeah feel free to edit it. Looks like some components aren't ready for darker color scheme. There are still some hard-coded colors, e.g.:
```
.tactical div.box.contents {
  background-color: white;
```
I'm done with changes, the main dashboard is usable for me. But there's still a plenty room for improvement, e.g. there might still be some hardly readable text in forms.

**Comment by lazyfrosch** [comment]
Tuned a lot of small bits, I guess we should squash changes later.

@lippserd your opinion? Especially on module specific styles here...

Here are screenshots:
login
dashboard
monitoring
monitoring-tactical
director-activity
director-edit
director-template

**Comment by deric** [comment]
@lazyfrosch Well done! Looks good, thanks.

**Comment by freddy4711** [comment]
Looks really nice. Looking forward to have this in my icinga installation :)

**Comment by lippserd** [comment]
Hi,

Thanks for the theme and updates to @deric and @lazyfrosch.

Cheers,
Eric

**Pull request merged**
