### PR TITLE
ui: Show problem badges in collapsed sidebar

### LINKED ISSUE #3568: Collapsed sidebar does not highlight problems
## Expected Behavior

I want to see that there are unhandled problems when collapsing the sidebar

## Current Behavior

Full-with sidebar shows System Issues (monitoring backend not running), module warnings (pending Director changes), unhandled issues (monitoring module). Collapsed sidebar does not provide this information.

## Possible Solution

Collapsed sidebar could either colorize the related icon with the corresponding problem-color or show a mini-badge in the upper/lower right corner, slightly overlapping the icon.

### PR DESCRIPTION
**Pull request by nilmerg**
fixes #3568

### CODE REVIEW

**Comment by flourish86** [comment]
This would be the css for `text-overflow: ellipsis`;

```
#layout:not(.minimal-layout).sidebar-collapsed #menu .nav-level-1 > .nav-item.active > a > .badge {
    max-width: 4.5em;
    overflow: hidden;
    text-overflow: ellipsis;
}
```

**Comment by nilmerg** [comment]
Looks fine to me on chromium Bildschirmfoto von 2019-07-03 07-44-01. Just with firefox it looks cropped somehow Bildschirmfoto von 2019-07-03 07-44-39. But we're seeing a million problems here. I guess if the number gets cropped in this case that's the least thing you're worried about. :thinking: :rofl:

**Comment by flourish86** [comment]
> I guess if the number gets cropped in this case that's the least thing you're worried about. 🤔 🤣

Maybe. But the UI should be able to handle that anyway. Especially since the only thing it requires 3 LoC.

**Comment by lippserd** [comment]
And we support high numbers of problems in the tactical overview as well.

**Comment by nilmerg** [comment]
So, I think I've got us covered:  Bildschirmfoto von 2019-07-03 11-28-17 Bildschirmfoto von 2019-07-03 11-28-32 Bildschirmfoto von 2019-07-03 11-28-55 Bildschirmfoto von 2019-07-03 11-29-19

**Pull request merged**
