### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by hailthemelody**
wasn't sure which branch to apply this to, and since it's not a feature i applied to master.

### CODE REVIEW

**Comment by nilmerg** [comment]
Hi,

thanks for your efforts to contribute to this project! But before I'll merge this into master, please squash your commits into a single one.

Thank you!

**Comment by hailthemelody** [comment]
Hello! I think I got it (it's my first rebase) see commit ae37ce6. I may have accidentally gone to far with the merge branch (commit 95b1190). Let me know if I need to undo anything - sorry for the hassle, learning Git.

**Comment by nilmerg** [comment]
Hey, how did you perform the rebase? The merge commit is usually not necessary for such small changes.

Please try the following:
Undo your rebase: git reset --hard 025b455
Redo your rebase: git rebase -i HEAD~2
Finally, force push your branch: git push -f origin master

The force push will ensure that all of your previous commits are replaced with the squashed one, as that's the actual purpose of this procedure. ;)

**Comment by hailthemelody** [comment]
Thanks very much for the detailed instructions @nilmerg ! I had done the same except I left `-f` out of `git push -f origin master`, which must have been why it was requiring that I merge the branch. All of my edits (including 4 additional I found since then) are now under the latest commit 146298e.

**Comment by nilmerg** [comment]
Thanks, looks good to me. Merged to master.

**Pull request closed without merging**
