### PR TITLE
Corrected kiosk mode config

### PR DESCRIPTION
**Pull request by log1-c**
Only got the documented steps to work if the [autologin] part was added, so I suppose it is missing from this documentation

### CODE REVIEW

**Review by nilmerg — CHANGES_REQUESTED** [review]
Please drop the example and link to `05-Authentication.md#authentication-configuration-external-authentication` instead. I also don't see a need for the configuration path here.

And please capitalize the first word of a new sentence. ;)

**Comment by log1-c** [comment]
@nilmerg 
Added the link (though I personally don't see the benefit of "jumping" to another docs page for just two lines of code).
Full path was used because it is used everywhere else in this docs page as well.

**Review by nilmerg — APPROVED** [review]
Well, ok, but the link points to the main location where external auth is described. In case the config ever changes, it's just a single place to update.

**Comment by nilmerg** [comment]
Eh, and thank you :D

**Pull request merged**
