### PR TITLE
Update Russian localization

### PR DESCRIPTION
**Pull request by krote5k**
Russian localization for icinga2 web. If possible, I will finish the translation.

### CODE REVIEW

**Comment by nilmerg** [comment]
Hi, are you still working on this?

Version 2.8 (stable) is not yet released, so you still have the chance to get this into the upcoming release!

**Comment by krote5k** [comment]
> 
> 
> Hi, are you still working on this?
> 
> Version 2.8 (stable) is not yet released, so you still have the chance to get this into the upcoming release!

Yes, the translation is still in progress-so I'll hurry up ))

**Comment by krote5k** [comment]
Translate complete.

**Comment by krote5k** [comment]
For or instead of "Resolve conflicts" can I make a new Pull request with a corrected translation (in Poedit)?

**Comment by nilmerg** [comment]
The conflicts will still re-appear with a new pull request. If you don't feel comfortable resolving them yourself I can do it for you.

**Comment by krote5k** [comment]
Let's try it. Attempt 2

**Comment by nilmerg** [comment]
Hi Dmitriy,

we are currently in the process to move our translation files from separate repositories into a single repository. That's https://github.com/Icinga/L10n.
Please open a new PR over there and include your current progress.

To aid you with that I prepared your current version of `application/locale/ru_RU/LC_MESSAGES/icinga.po` and attached it wrapped in a zip file. <sup>(1)</sup>
Just extract the file and put it in the new repository's location. (`src/ru_RU/LC_MESSAGES/icinga.po`, Overwrite the existing file) Then follow the remaining steps (outlined [here](https://github.com/Icinga/L10n/blob/master/CONTRIBUTING.md)) and create the PR.

If you have questions or run into problems don't hesitate to ask me for help. :)

¹ [icinga.po.zip](https://github.com/Icinga/icingaweb2/files/4556516/icinga.po.zip)

**Comment by krote5k** [comment]
I'm not a big expert on POEdit and I don't know how to add the plural form of words yet

Tabs (n ->) - not for this?

**Comment by nilmerg** [comment]
The tabs show you which form is for which definition of an amount of things. The numbers are examples for what might be the amount `n`. I don't know russian :sweat_smile: but I know that there are three different plural forms and these tabs show you which form is used when.

**Comment by nilmerg** [comment]
Superseded by https://github.com/Icinga/L10n/pull/5

**Pull request closed without merging**
