### PR TITLE
[WIP] Add file storage abstraction

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
@lippserd This is not to be merged yet. I'll also implement all this prototyped stuff once you give green light.

**Comment by Al2Klimov** [comment]
@lippserd "Do you have a use case for `getLocalPath()`?" – Unfortunately... no. I have three of them:
* `curl_setopt($ch, CURLOPT_CAINFO, $storage->getLocalPath(...));`
* `curl_setopt($ch, CURLOPT_SSLCERT, $storage->getLocalPath(...));`
* `curl_setopt($ch, CURLOPT_SSLKEY, $storage->getLocalPath(...));`

**Comment by Al2Klimov** [comment]
... and I guess a lot of people will have similar ones in combination w/ a remote storage. (And adding methods to interfaces afterwards is evil.)

**Comment by Al2Klimov** [comment]
@lippserd Yet another one: [`RestApiResourceForm::includeTlsClientIdentity()`](https://github.com/Icinga/icingaweb2/blob/4860f12d3b9241973faa025c687f43f5e93c9929/application/forms/Config/Resource/RestApiResourceForm.php)

**Comment by lippserd** [comment]
Looks good. Please proceed with the concrete implementation :)

Default mode for directories should be `2770` and default mode for files should be `0664`.

**Comment by Al2Klimov** [comment]
"Default mode" – Do we have a non-default one? And why should files be world-readable if the directories aren't?

**Comment by Al2Klimov** [comment]
So, what does the @lippserd say?

**Pull request merged**
