### PR TITLE
Support PHP 8.1

### LINKED ISSUE #4609: Support for PHP 8.1
## Describe the bug
The PHP 8 support in Icingaweb2 is not sufficient to work with PHP 8.1.

Accessing `/icingaweb2` results in:
```
Deprecated: Return type of Icinga\Application\Libraries::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Libraries.php on line 20

Deprecated: Return type of Icinga\Application\Config::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Config.php on line 125

Deprecated: Return type of Icinga\Application\Config::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Config.php on line 145

Deprecated: Return type of Icinga\Application\Config::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Config.php on line 175

Deprecated: Return type of Icinga\Application\Config::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Config.php on line 165

Deprecated: Return type of Icinga\Application\Config::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Config.php on line 155

Deprecated: Return type of Icinga\Application\Config::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Config.php on line 135

Deprecated: Return type of Icinga\Web\Session\SessionNamespace::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Web/Session/SessionNamespace.php on line 35

Deprecated: Return type of Zend_Controller_Action_HelperBroker_PriorityStack::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker/PriorityStack.php on line 91

Deprecated: Return type of Zend_Controller_Action_HelperBroker_PriorityStack::offsetExists($priorityOrHelperName) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker/PriorityStack.php on line 102

Deprecated: Return type of Zend_Controller_Action_HelperBroker_PriorityStack::offsetGet($priorityOrHelperName) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker/PriorityStack.php on line 117

Deprecated: Return type of Zend_Controller_Action_HelperBroker_PriorityStack::offsetSet($priority, $helper) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker/PriorityStack.php on line 137

Deprecated: Return type of Zend_Controller_Action_HelperBroker_PriorityStack::offsetUnset($priorityOrHelperName) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker/PriorityStack.php on line 173

Deprecated: Return type of Zend_Controller_Action_HelperBroker_PriorityStack::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker/PriorityStack.php on line 198

Deprecated: Return type of Zend_View_Helper_Placeholder_Container_Standalone::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/icingaweb2/library/vendor/Zend/View/Helper/Placeholder/Container/Standalone.php on line 317

Deprecated: Return type of Zend_View_Helper_Placeholder_Container_Standalone::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/icingaweb2/library/vendor/Zend/View/Helper/Placeholder/Container/Standalone.php on line 261

Deprecated: Return type of Zend_View_Helper_Placeholder_Container_Standalone::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/icingaweb2/library/vendor/Zend/View/Helper/Placeholder/Container/Standalone.php on line 273

Deprecated: Return type of Zend_View_Helper_Placeholder_Container_Standalone::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/icingaweb2/library/vendor/Zend/View/Helper/Placeholder/Container/Standalone.php on line 284

Deprecated: Return type of Zend_View_Helper_Placeholder_Container_Standalone::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/icingaweb2/library/vendor/Zend/View/Helper/Placeholder/Container/Standalone.php on line 296

Deprecated: Return type of Zend_View_Helper_Placeholder_Container_Standalone::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/icingaweb2/library/vendor/Zend/View/Helper/Placeholder/Container/Standalone.php on line 307

Deprecated: Return type of Zend_Paginator::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/icingaweb2/library/vendor/Zend/Paginator.php on line 513

Deprecated: Return type of Zend_Paginator::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/icingaweb2/library/vendor/Zend/Paginator.php on line 815

Deprecated: Return type of Icinga\Authentication\AuthChain::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Authentication/AuthChain.php on line 200

Fatal error: Uncaught ErrorException: Uncaught Zend_Controller_Response_Exception: Cannot send headers; headers already sent in /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker/PriorityStack.php, line 30 in /usr/share/icingaweb2/library/vendor/Zend/Controller/Response/Abstract.php:321 Stack trace: #0 /usr/share/icingaweb2/library/vendor/Zend/Controller/Response/Abstract.php(148): Zend_Controller_Response_Abstract->canSendHeaders() #1 /usr/share/php/Icinga/Web/Response.php(356): Zend_Controller_Response_Abstract->setRedirect() #2 /usr/share/php/Icinga/Web/Response.php(407): Icinga\Web\Response->prepare() #3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Response/Abstract.php(762): Icinga\Web\Response->sendHeaders() #4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(975): Zend_Controller_Response_Abstract->sendResponse() #5 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch() #6 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch() #7 /usr/share/icingaweb2/public/index.php(4): require_once('...') #8 {main} thrown in /usr/share/icingaweb2/library/vendor/Zend/Controller/Response/Abstract.php:321 Stack trace: #0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}() #1 {main} Next Zend_Controller_Exception: Uncaught Zend_Controller_Response_Exception: Cannot send headers; headers already sent in /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker/PriorityStack.php, line 30 in /usr/share/icingaweb2/library/vendor/Zend/Controller/Response/Abstract.php:321 Stack trace: #0 /usr/share/icingaweb2/library/vendor/Zend/Controller/Response/Abstract.php(148): Zend_Controller_Response_Abstract->canSendHeaders() #1 /usr/share/php/Icinga/Web/Response.php(356): Zend_Controller_Response_Abstract->setRedirect() #2 /usr/share/php/Icinga/Web/Response.php(407): Icinga\Web\Response->prepare() #3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Response/Abstract.php(762): Icinga\Web\Response->sendHeaders() #4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(975): Zend_Controller_Response_Abstract->sendResponse() #5 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch() #6 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch() #7 /usr/share/icingaweb2/public/index.php(4): require_once('...') #8 {main} thrown#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}() #1 {main} in /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php:259 Stack trace: #0 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(906): Zend_Controller_Plugin_Broker->routeShutdown() #1 /usr/share/php/Icinga/Application/Web.php(471): Zend_Controller_Front->dispatch() #2 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}() #3 {main} thrown in /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 259
```

Lots of deprecations also when running `icingacli`:
```
# icingacli help setup
PHP Deprecated:  Return type of Icinga\Application\Libraries::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Libraries.php on line 20

Deprecated: Return type of Icinga\Application\Libraries::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Libraries.php on line 20
PHP Deprecated:  Return type of Icinga\Application\Config::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Config.php on line 125

Deprecated: Return type of Icinga\Application\Config::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Config.php on line 125
PHP Deprecated:  Return type of Icinga\Application\Config::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Config.php on line 145

Deprecated: Return type of Icinga\Application\Config::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Config.php on line 145
PHP Deprecated:  Return type of Icinga\Application\Config::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Config.php on line 175

Deprecated: Return type of Icinga\Application\Config::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Config.php on line 175
PHP Deprecated:  Return type of Icinga\Application\Config::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Config.php on line 165

Deprecated: Return type of Icinga\Application\Config::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Config.php on line 165
PHP Deprecated:  Return type of Icinga\Application\Config::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Config.php on line 155

Deprecated: Return type of Icinga\Application\Config::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Config.php on line 155
PHP Deprecated:  Return type of Icinga\Application\Config::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Config.php on line 135

Deprecated: Return type of Icinga\Application\Config::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Icinga/Application/Config.php on line 135
PHP Deprecated:  preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /usr/share/php/Icinga/Application/Cli.php on line 126

Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /usr/share/php/Icinga/Application/Cli.php on line 126
PHP Deprecated:  preg_quote(): Passing null to parameter #1 ($str) of type string is deprecated in /usr/share/php/Icinga/Cli/Loader.php on line 279

Deprecated: preg_quote(): Passing null to parameter #1 ($str) of type string is deprecated in /usr/share/php/Icinga/Cli/Loader.php on line 279
USAGE: icingacli setup <command> [<action>] [options]

Available commands:

  config
  token

Show help on a specific command: icingacli help setup <command>
```

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Install icingaweb2 Debian packages in an unstable environment
2. Add experimental apt sources
   ```
   echo "deb http://deb.debian.org/debian/ experimental main contrib non-free" >> /etc/apt/sources.list
   echo "deb-src http://deb.debian.org/debian/ experimental main contrib non-free" >> /etc/apt/sources.list
   ```
3. Install php8.1 packages from experimental: 
   ```
   apt update && apt install -t experimental libapache2-mod-php8.1 php8.1-{cli,curl,gd,intl,ldap,mbstring,mysql,opcache,pgsql,readline,soap,xml}
   ```
4. Enable mod_php8.1:
   ```
   a2enmod php8.1
   systemctl restart
   ```
5. `w3m http://localhost/icingaweb2`

## Expected behavior
Web interface works as expected

## Screenshots
N/A

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.9.5
* Web browser used: N/A
* Icinga 2 version used (`icinga2 --version`):
   ```
   icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.2-1)
   
   Copyright (c) 2012-2021 Icinga GmbH (https://icinga.com/)
   License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
   This is free software: you are free to change and redistribute it.
   There is NO WARRANTY, to the extent permitted by law.
   
   System information:
     Platform: Debian GNU/Linux
     Platform version: Unknown
     Kernel: Linux
     Kernel version: 5.14.0-4-amd64
     Architecture: x86_64
   
   Build information:
     Compiler: GNU 11.2.0
     Build host: x86-ubc-02
     OpenSSL version: OpenSSL 1.1.1l  24 Aug 2021
   
   Application information:
   
   General paths:
     Config directory: /etc/icinga2
     Data directory: /var/lib/icinga2
     Log directory: /var/log/icinga2
     Cache directory: /var/cache/icinga2
     Spool directory: /var/spool/icinga2
     Run directory: /run/icinga2
   
   Old paths (deprecated):
     Installation root: /usr
     Sysconf directory: /etc
     Run directory (base): /run
     Local state directory: /var
   
   Internal paths:
     Package data directory: /usr/share/icinga2
     State path: /var/lib/icinga2/icinga2.state
     Modified attributes path: /var/lib/icinga2/modified-attributes.conf
     Objects path: /var/cache/icinga2/icinga2.debug
     Vars path: /var/cache/icinga2/icinga2.vars
     PID path: /run/icinga2/icinga2.pid
   ```
* PHP version used (`php --version`):
   ```
      PHP 8.1.0RC5 (cli) (built: Nov  4 2021 14:57:08) (NTS)
   Copyright (c) The PHP Group
   Zend Engine v4.1.0-dev, Copyright (c) Zend Technologies
       with Zend OPcache v8.1.0RC5, Copyright (c), by Zend Technologies
   ```
* Server operating system and version: Debian GNU/Linux bookworm/sid

## Additional context

 * https://github.com/php/php-src/blob/PHP-8.1/NEWS
 * https://github.com/php/php-src/blob/PHP-8.1/UPGRADING
 * https://github.com/php/php-src/blob/PHP-8.1/UPGRADING.INTERNALS

### PR DESCRIPTION
**Pull request by Thomas-Gelf**
Contains a bunch of fixes for PHP 8.1 warning. There might be more, but some of them are hard to spot. Have been running this branch rebased on 2.9.x for a while on 8.1 right now without facing issues.

### CODE REVIEW

**Comment by nilmerg** [comment]
Good job, really good job. I've now wasted an entire work day myself, thank you for not telling me this. Now I even have to diff this to ensure nothing gets lost. :tada:

**Comment by Thomas-Gelf** [comment]
@nilmerg: told you on [November 25](https://github.com/Icinga/icingaweb2/issues/4609#issuecomment-978883145), the branch has been linked there and got just a very few modifications since then.

**Comment by nilmerg** [comment]
You're not assigned to the issue, and from the comment I've only extracted that you're gonna fix this on *your* personal work. i.e. Director and such. That's even emphasized by the screenshot. By this week I've only seen you changing exactly this, Director and gipfl stuff. No pull request on here and do you really think I keep track of every single branch on here?

**Comment by Thomas-Gelf** [comment]
> You're not assigned to the issue [..]

#4609? Neither are you. You complained and wanted to postpone it. I offered my help, pushed and mentioned [7cad471](https://github.com/Icinga/icingaweb2/commit/7cad471) the very next day. Promised to watch it for some time, to see if there is more that needs to be fixed. Did so.

I don't see it, but anyway: sorry for my wrongdoing.

**Comment by nilmerg** [comment]
I don't have to, it's me who's assigning such complicated topics in the first place. I wanted to postpone it not just by chance. I've had no idea at that time when which distribution is going to ship a stable with PHP 8.1. Now that I know that, we **are** going to postpone this until the end of April when we plan to release v2.11.

v2.11 will drop support for PHP 5.6 to 7.1, as promised in the upgrading notes of v2.9. PHP 7.2 will only still be supported because of a single ubuntu release that is only EOL after April 2023. So, no need for these weird comments all over the code.

Since I know that you have your own ideas if it's about compatibility with legacy PHP versions, I didn't told you my objections in more detail **because** I didn't expect you to attempt to patch Icinga Web 2 in such a prematurely manner.

So this is just due to bad communication, of which we are *both* guilty.

To counteract this right here: I won't accept this pull request due the reasons outlined above. I'm assigned to the issue now and will open my own pull request which attempts to solve PHP 8.1 support with proper return type declarations. All other changes that I didn't found on my own already, I will cherry-pick from here.

**Pull request closed without merging**
