### PR TITLE
CSS: Adjust application state summary notification design

### LINKED ISSUE #4530: Adapt new notification design for #application-state-summary
The #application-state-summary element has a different design than #notifications.

Screen Shot 2021-09-08 at 15 36 39

### PR DESCRIPTION
**Pull request by Yonas-net**
resolves #4530

### CODE REVIEW

**Review by nilmerg — CHANGES_REQUESTED** [review]
It's not just the left margin, but also the style that's incorrect.

Screenshot from 2021-09-22 11-17-24
Screenshot from 2021-09-22 11-18-53

**Review by flourish86 — APPROVED** [review]
Looks perfect now. 🎉

Screen Shot 2021-09-29 at 13 09 10

**Comment by nilmerg** [comment]
And the font color? It's white on red for the errors, not black on red.

**Comment by nilmerg** [comment]
Whooops, never mind. :thinking: :roll_eyes:  :man_facepalming:

**Review by nilmerg — APPROVED** [review]

**Pull request merged**
