### PR TITLE
Add contact and contactgroup filters

### LINKED ISSUE #2708: Add contact and contactgroup filters (not for restrictions)
It would be great if you could filter for hosts/services which alert to a specific contactgroup. For example something like:

/icingaweb2/monitoring/list/services?service_hard_state=1&service_contactgroup=\*team1\*

### PR DESCRIPTION
**Pull request by lippserd**
fixes #2708

### CODE REVIEW

**Comment by lippserd** [comment]
Combined group membership filters are not yet implemented for contacts and contact groups.

**Comment by lippserd** [comment]
Decided against supporting combined group membership filters for the moment. This would require changes to our contact and contactgroup queries for which we don't have the time.

**Comment by lippserd** [comment]
Had a typo in the service_contactgroup column. Though it is intended that service_contact and service_contactgroup filters only work for services and service groups. I wanted to keep that as minimal as possible. Hosts and Host groups only support host_contact and hostgroup_contact.

**Comment by nilmerg** [comment]
Choosing `Service Contactgroup` now fails with this error: `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'scg.contact_object_id' in 'on clause'`

**Comment by lippserd** [comment]
Done.

**Pull request merged**
