### PR TITLE
add MariaDB to installation doc

### PR DESCRIPTION
**Pull request by robertsilen**
as discussed in https://github.com/Icinga/icingaweb2/issues/5237

### CODE REVIEW

**Review by nilmerg — COMMENTED** [review]
MySQL is also exclusively mentioned in `05-Authentication.md` and `07-Preferences.md`, just in case you'd like to adjust these as well.

**Comment by robertsilen** [comment]
> MySQL is also exclusively mentioned in `05-Authentication.md` and `07-Preferences.md`, just in case you'd like to adjust these as well.

Thanks, I added now

**Review by nilmerg — APPROVED** [review]

**Comment by robertsilen** [comment]
Thank you! Well will this turn up at https://icinga.com/docs/icinga-web/2.8/doc/02-Installation/ ?

**Comment by nilmerg** [comment]
No, as mentioned in the other PR, it only turns up in the latest version of the documentation. Currently, since this change isn't part of a release yet, it doesn't.

**Pull request merged**
