### PR TITLE
RELEASE.md: add Docker preparations

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by nilmerg** [comment]
That's [already there](https://github.com/Icinga/icingaweb2/blob/master/RELEASE.md#docker)?

**Comment by nilmerg** [comment]
Or, why should we have a note here that a different repo *may* need updates?

Following this, we'd also need a note that we should ensure monitoring module still works with the IDO.
Or that Icinga DB Web works with Icinga DB.

I see no point in this.

**Comment by Al2Klimov** [comment]
No, at that time you're just replicating the already finalized tag which may have bugs like docker-icingaweb2#41 .

This one encourages you to fix such before the release GHA even run.

**Comment by nilmerg** [comment]
That's too late. Such should happen waaaay before the actual release. Just as it happened today.

**Comment by Al2Klimov** [comment]
Even better. :)

**Pull request closed without merging**
