### PR TITLE
Bugfix/use a more secure hash algorithm for passwords 11838

### LINKED ISSUE #2436: [dev.icinga.com #11838] Use a slower and more secure hash algorithm than MD5 for password hashing
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11838

**Created by JamesForman on 2016-05-25 06:53:42 +00:00**

Assignee: _elippmann_
Status: _Feedback_ 
Target Version: _Backlog_
Last Update: _2016-12-15 12:57:55 +00:00 (in Redmine)_

---

Icinga Web 2 is currently using a single round unsalted MD5 hash for user passwords stored in the database, this should be upgraded to something modern and less vulnerable.

**Changesets**

_2016-12-15 12:07:20 +00:00_ by _(unknown)_ 2f78c8ab028bff789b679ad57f7fce4f45fc98ac

    Simplify DbUserBackend::authenticate()
    
    refs #11838

_2016-12-15 12:09:04 +00:00_ by _(unknown)_ b48740c63bdc2e393bbb97355e8f1cdca3eef6d5

    Drop DbUserBackend::getSalt()
    
    refs #11838

_2016-12-15 12:46:28 +00:00_ by _(unknown)_ d6448182f1f2c6a0cc04533fdc87ccb40cea87fd

    DbUserBackend: use SHA-512 (with 5001 to 10000 rounds) to hash passwords
    
    refs #11838

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #2436

### CODE REVIEW

**Comment by lippserd** [comment]
Hi Alex,

Instead of using a different hash algorithm I opt for using encryption, i.e. crypt blowfish.

Best regards,
Eric

**Comment by baurmatt** [comment]
It's best practice to hash passwords not encrypt them... Can please some review this? Would be great to get away from MD5...

Review from my side:
- What happens to current user passwords which are currently encrypted with MD5?

**Comment by Al2Klimov** [comment]
@baurmatt If it's like that, why PHP's function password_**hash** uses the **CRYPT**_BLOWFISH algo by default?

**Comment by lippserd** [comment]
My comment is a bit misleading indeed. In terms of bcrypt it should maybe read encryption based instead of just encryption. I'll update my comment.

My point here is not just to improve the hashing algorithm but to use a key derivation function which has been designed for password hashing like bcrypt, PBKDF2 or scrypt.

**Comment by baurmatt** [comment]
Ah now I get what you mean @lippserd. I absolutely agree! :)

**Comment by lippserd** [comment]
Closed in favor of #2954

**Pull request closed without merging**
