### PR TITLE
fixed powertools repo name for CentOS 8

### PR DESCRIPTION
**Pull request by log1-c**
name for the powertools changed to lowercase

### CODE REVIEW

**Comment by nilmerg** [comment]
If I search for this, I find other installation instructions which show both variations. Does this depend on a specific 8.x version or is somehow else dependent on something else? Do you have a source showing the case change, a news, changelog or such?

**Comment by log1-c** [comment]
It seems indeed being bound to specific versions, i.e. versions newer than 8.3.2011, which makes it event more annoying.
https://wiki.centos.org/Manuals/ReleaseNotes/CentOS8.2011#Yum_repo_file_and_repoid_changes.

So maybe having both variants might be the right approach.

**Comment by nilmerg** [comment]
> So maybe having both variants might be the right approach.

Fine, then consider this a change request :grin:

**Review by nilmerg — APPROVED** [review]
LGTM!

**Pull request merged**
