### PR TITLE
Added Kiosk Mode in doc

### PR DESCRIPTION
**Pull request by Wintermute2k6**
Added Kiosk Mode description, based on customer wish ref/NC/19457 & ref/NC/19599

### CODE REVIEW

**Comment by Wintermute2k6** [comment]
false reference should be ref/IP/19457 & ref/IP/19599

**Comment by nilmerg** [comment]
Isn't this more of a how-to which should be published on [community.icinga.com/c/howto](https://community.icinga.com/c/howto)?

**Comment by dnsmichi** [comment]
@nilmerg I would prefer this being in the official docs, this question gets asked more than anything else.

**Comment by Wintermute2k6** [comment]
It was requested by our partners and it doesn't provide a negative effect and also frees up more time which can be spend with actual projects.

**Comment by nilmerg** [comment]
Just had a first proper look at it. Since this is related to #3286 I'd add a paragraph about it here as well. Though, this is also talking about a default autologin account, which wouldn't need a database user or even usergroup. Or is this on purpose mentioned?

**Comment by Wintermute2k6** [comment]
I think this would be very helpful ! Question would be how configureable this kiosk user would be just filters or would there be the possibility to separately adjust him in the roles ?

Thanks in advance !

**Comment by nilmerg** [comment]
An autologin user can be configured just the same as every other user. A role just needs to define that it applies to the user's name. (i.e. `kiosk`) Then no database is required.

**Pull request merged**
