### PR TITLE
Check if url is external in validation function

### PR DESCRIPTION
**Pull request by ValeDaRold**
This PR fixes issue: #4970

### CODE REVIEW

**Comment by nilmerg** [comment]
This has originally been adjusted to allow sub domains: c2f74d49cbb49c3b201ff528491efc39367c8080

While it fixes the current issue, it breaks the old one. This requires a more sophisticated fix.

**Comment by ValeDaRold** [comment]
Hi @nilmerg!
Thank you for your quick answer.
I got your point and this solution can't work for subdomains. What about updating directly the Url.php class in addition to the change already committed in this PR?
At line 181 we can change the code as follow for accepting subdomains and fixing the problem reported in the issue:
```
        $urlParts = parse_url($url);
        $serverName = str_replace('.', '\.',$request->getServer('SERVER_NAME'));
        if (isset($urlParts['scheme']) && (
            $urlParts['scheme'] !== $request->getScheme()
            || (isset($urlParts['host']) && preg_match("/^([\w\-\.]+\.)?$serverName$/", $urlParts['host']) !== 1)
            || (isset($urlParts['port']) && $urlParts['port'] != $request->getServer('SERVER_PORT')))
        ) {
            $urlObject->setIsExternal();
        }
```

**Comment by nilmerg** [comment]
I don't like changing the meaning of *external* on URL objects. Maybe a new method `getDomainName` which returns `'c.com'` for `'b.c.com'` and `'a.b.c.com'`?

**Comment by ValeDaRold** [comment]
Hi @nilmerg!
As agreed with @lippserd, we wait for your best fix (which should be released within the week).
We are available for help, if necessary. :)

**Comment by nilmerg** [comment]
We came to the conclusion that this change is sufficient. Thank you!

**Review by nilmerg — APPROVED** [review]

**Pull request merged**
