### PR TITLE
Dashboard: handle URLs with leading /

### LINKED ISSUE #2804: Leading "/" in URL makes dashboard unusable
adding a url with "/" as prefix resutls in a non recoverable error.
e.g. "/monitoring/list/services?service_state!=0&service_acknowledged=0"
this issue is related to #2452

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #2804

### CODE REVIEW

**Comment by Al2Klimov** [comment]
As discussed w/ @lippserd (offline): We want the URLs not to be changed automatically.

This one ensures that.

**Comment by lippserd** [comment]
Hi Alex,

This is no longer necessary, right?

Cheers,
Eric

**Comment by Al2Klimov** [comment]
It is necessary.

**Comment by Al2Klimov** [comment]
https://github.com/Icinga/icingaweb2/pull/3229#issuecomment-358269633

**Pull request closed without merging**
