### PR TITLE
Fix incorrect history time and date

### LINKED ISSUE #4853: wrong time in history overview
## Describe the bug
History of services is showing the same time in the overview. In the detailed view the displayed times are correct.

## To Reproduce
Choose host -> service -> history -> all times are the same.
Click on a single entry in history and the correct time is shown with the details.

## Expected behavior
Correct times in the overview

## Screenshots
icingaweb2

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):  Icinga Web 2 Version | 2.11.0
* Web browser used: Firefox and Chrome current versions
* Icinga 2 version used (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.4-1)
* PHP version used (`php --version`): PHP 7.4.28 (cli) (built: Feb 17 2022 16:17:19) ( NTS )
* Server operating system and version: System information:
  Platform: Debian GNU/Linux
  Platform version: 11 (bullseye)
  Kernel: Linux
  Kernel version: 5.10.0-8-amd64
  Architecture: x86_64

## Additional context
-

### PR DESCRIPTION
**Pull request by nilmerg**
fixes #4853

### CODE REVIEW

**Review by adriangalbincea — COMMENTED** [review]
I tested these changes to my environment and I can confirm that the timestamps show fine but Timeline page errors
ice_screenshot_20220703-093915

**Review by sukhwinder33445 — DISMISSED** [review]

**Review by yhabteab — DISMISSED** [review]
### Before

Bildschirmfoto 2022-07-04 um 09 58 59

### After

Bildschirmfoto 2022-07-04 um 10 00 16

**Comment by nilmerg** [comment]
Thanks, though it's not finished yet. The overdue dashboard is still broken.

**Comment by nilmerg** [comment]
Looks fine to me. Please re-test @sukhwinder33445 @yhabteab **with postgres enabled**

**Comment by adriangalbincea** [comment]
> Looks fine to me. Please re-test @sukhwinder33445 @yhabteab **with postgres enabled**

Hey, not sure if is finished, but for me, nothing under history is working. errors on each page...
"A non well formed numeric value encountered"

**Comment by nilmerg** [comment]
Acknowledgement events look fine to me here as well.

**Review by sukhwinder33445 — APPROVED** [review]

**Comment by adriangalbincea** [comment]
> Looks fine to me. Please re-test @sukhwinder33445 @yhabteab **with postgres enabled**

You are right, the new acknowledgements have the correct timestamp.
Is there a way of getting rid of old incorrect acknowledgements?

**Comment by nilmerg** [comment]
There are no *old* or *new* acknowledgements with regard to the issue that's being fixed here. Timestamps were incorrectly retrieved from the database, no matter the age of individual events.

**Comment by nilmerg** [comment]
I don't know. Please note that `01:33:42` was only the result of the incorrectly retrieved timestamps. The actual timestamps in the database were never wrong, at least not because of Icinga Web.

**Comment by nilmerg** [comment]
Have you maybe a cache that stores query results, and the results you see are outdated? Then wipe the cache and the issue should be gone.

**Comment by adriangalbincea** [comment]
Correct, the PHP was adjusted to pull the right timestamps.

**Comment by adriangalbincea** [comment]
@nilmerg I found out that if I acknowledge a host, I get the incorrect timestamp but for service is correct. Did I miss updating a php file?
ice_screenshot_20220705-144141

**Comment by nilmerg** [comment]
Works fine for me.

> Did I miss updating a php file?

Maybe. That'd be `modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicecommenthistoryQuery.php`.

**Comment by adriangalbincea** [comment]
Was the HostcommenthistoryQuery.php works fine now.

**Pull request merged**
